### ISSUE TITLE
skin

### ISSUE THREAD

**Issue by TonTonSheitan** [indilo53/fivem-esx_fishermanjob#1]
Hi can you tell me how i can find the variation to change the skin of each craft, i find nothing on google thanks.

**Comment by ig0ne** [comment]
Tu peux reset le skin de ton perso et noter le numéro de chaque objets que tu change (ex: pantalon1: 53 pantalon2: 2, shirt1: 35, shirt2, 6 ...) ensuite tu vas dans la Bdd, dans job_grades tu fais "modifier" sur le job que tu veux et dans "skin male" et "skin female" tu change les numéros des objets par ceux que tu as trouvé ;)

Ps: les Objets1 se sont les skins et les Objets2 se sont les variations de couleurs

**Comment by TonTonSheitan** [comment]
Ouep j'ai vu comment on fais pour changer je chercher un site internet qui repére tout les object mais je le fais avec le lambda menu c'est beaucoup mieux, et merci pour ta réponse ;)

**Comment by ig0ne** [comment]
https://marekkraus.sk/gtav/skins/ je pense que c'est ça que tu cherche :)

**Comment by TonTonSheitan** [comment]
Ah oui nice, Merci bien :D


________________________________
De : ig0ne <notifications@github.com>
Envoyé : lundi 22 mai 2017 05:22
À : indilo53/fivem-esx_fishermanjob
Cc : TonTonSheitan; Author
Objet : Re: [indilo53/fivem-esx_fishermanjob] skin (#1)


https://marekkraus.sk/gtav/skins/ je pense que c'est ça que tu cherche :)
